### ISSUE TITLE
add imagescale vocabulary

### ISSUE THREAD

**Issue by thet** [plone/plone.app.vocabularies#11]
A image scale vocabulary could be of general interest. I regularly need one.
Here is a blueprint:
https://github.com/collective/collective.folderishtypes/blob/master/collective/folderishtypes/vocabularies.py

**Comment by hvelarde** [comment]
:+1: @rodfersou and I were talking about the same today and this package is the place to store it.

**Comment by rodfersou** [comment]
:+1:
