### ISSUE TITLE
Principals Vocab

### ISSUE THREAD

**Issue by Gomez** [plone/plone.app.vocabularies#13]
For a project i created a rough principals vocabularies. It started as a copy of the users vocab and works right now (temporary) for our project. I am willing to do it the "right" way, just need some advice.
Can some1 look at it, and gimme advice: 
https://github.com/starzel/plone.app.vocabularies/tree/add_principals

**Comment by jensens** [comment]
relates to PR #19

**Comment by jensens** [comment]
superseded by #56
