### ISSUE TITLE
vocabulary="plone.app.vocabularies.Users" AttributeError: acl_users

### ISSUE THREAD

**Issue by jianaijun** [plone/plone.app.vocabularies#14]
plone 4.3.6 
plone.app.contenttypes 1.1b5
plone.app.vocabularies 2.1.17 |  2.1.18

```
user_search_filter = schema.Dict(
    title=_(u"User search filter constraint"),
    description=_(u"User search filter constraint"),
    required=False,
    key_type=schema.Choice(
        title=_(u"User"),
        vocabulary="plone.app.vocabularies.Users",
        required=True),
    value_type=schema.ASCIILine(
        title=_(u"Condition"),
        description=_(u"Use this setting to value for user. "
                      u"there are options available: "),
        required=True)
)
```

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 50, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module z3c.form.form, line 135, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module z3c.form.browser.multi, line 63, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 479, in update
  Module z3c.form.widget, line 111, in update
  Module zope.schema._field, line 646, in bind
  Module zope.schema._field, line 352, in bind
  Module Zope2.App.schema, line 33, in get
  Module plone.app.vocabularies.users, line 111, in __call__
  Module Products.CMFCore.utils, line 10, in check_getToolByName
  Module Products.CMFCore.utils, line 120, in getToolByName
AttributeError: acl_users

---

Use "plone.app.vocabularies.Groups" instead of "plone.app.vocabularies.Users", is working properly.

```
user_search_filter = schema.Dict(
    title=_(u"User search filter constraint"),
    description=_(u"User search filter constraint"),
    required=False,
    key_type=schema.Choice(
        title=_(u"User"),
        vocabulary="plone.app.vocabularies.Groups",
        required=True),
    value_type=schema.ASCIILine(
        title=_(u"Condition"),
        description=_(u"Use this setting to value for user. "
                      u"there are options available: "),
        required=True)
)
```

**Comment by jensens** [comment]
fun fact: both vocabularies are using ``getToolByName(context, "acl_users")`` in their init, so i really dont get whats the difference is.

**Comment by ale-rt** [comment]
Maybe the context is broken or it is None (happens in some scripts when the portal is not configured,  getSite() will return None)

**Comment by jensens** [comment]
In refactored #56 I uses getSite() to get the acl_users instead of context to overcome the problem, which occured for me only in some kinds of more or less unbound z3cforms.
