### ISSUE TITLE
KeywordsVocabulary - make keyword_index dynamic

### ISSUE THREAD

**Issue by mtrebron** [plone/plone.app.vocabularies#44]
The z3cform AjaxSelectWidget (select2) is able to supply a keyword index field:

```
    <field name="my_field" type="zope.schema.Tuple" lingua:independent="true">
      <description>A keyword query</description>
      <required>False</required>
      <title>Custom Keyword</title>
      <value_type type="zope.schema.Choice">
        <vocabulary>plone.app.vocabularies.Keywords</vocabulary>
        <field>my_field</field>        
        <orderable>True</orderable>
      </value_type>
      <form:widget type="plone.app.z3cform.widget.AjaxSelectFieldWidget" />
    </field>
```

This requires a keyword index "my_field" in the portal catalog. 

It is trivial to implement:

```
    def all_keywords(self, keyword_index, kwfilter):
        site = getSite()
        self.catalog = getToolByName(site, 'portal_catalog', None)
        if self.catalog is None:
            return SimpleVocabulary([])
        try:
            index = self.catalog._catalog.getIndex(keyword_index)
        except KeyError:
            index = self.catalog._catalog.getIndex(self.keyword_index)
            
        return safe_simplevocabulary_from_values(index._index, query=kwfilter)


    def __call__(self, context, query=None):
        section = self.section(context)
        keyword_index = context and context.REQUEST.get('field', self.keyword_index)
        if section is None:
            return self.all_keywords(keyword_index, query)
        return self.keywords_of_section(section, keyword_index, query)
```

**Comment by jensens** [comment]
For the common case ``indexname==fieldname`` this is a great convenience. 

I just do not understand why one needs the try-except in ``all_keywords``.
If you do in ``__call__`` a ``keyword_index = context.REQUEST.get('field', self.keyword_index) if context else self.keyword_index`` instead this should not be needed, or am I wrong?

Would you mind to provide a pull request? In the case of yes: then the Plone Foundation requires a Contributor Agreement from you. Please visit https://plone.org/foundation/contributors-agreement and follow the instructions to become a Plone core contributor.

**Comment by mtrebron** [comment]
When editing existing content, 
```
keyword_index = context.REQUEST.get('field', self.keyword_index) if context else self.keyword_index
```
seems to work. But, for me, adding a new document results in 
```
2017-03-01 11:47:50 ERROR Zope.SiteErrorLog 1488365270.910.867282256349 http://localhost:8585/mdb/++add++test_document_type/@@getVocabulary
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.vocabulary, line 101, in __call__
  Module mdb_theme.monkey_patches, line 214, in pac_browser_get_vocabulary
  Module mdb_theme.monkey_patches, line 260, in pav_cat_call
AttributeError: 'DefaultAddView' object has no attribute 'REQUEST'
```

I'd have to look and see if my patched version of p.a.c is responsible for this...

Also, I see that all_keywords is executed twice when viewing, editing, and clicking the field:

got an index for Subject
got an index for Subject

got an index for Subject
got an index for Subject

got an index for Subject
got an index for my_field

Re contributing, it has been on my to do list...

**Comment by mtrebron** [comment]
@jensens 

When adding a new document and selecting the field, @@getVocabulary returns zero results.

Your suggestion for the call method results in an AttributeError: the DefaultAddView context has no REQUEST

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.vocabulary, line 101, in __call__
  Module plone.app.content.browser.vocabulary, line 326, in get_vocabulary
  Module mdb_theme.monkey_patches, line 294, in pav_cat_call
AttributeError: 'DefaultAddView' object has no attribute 'REQUEST'
```

Also, attempting to update the values and save, results in  zope.schema._field raising a ConstraintNotSatisfiedError because the values are not in the KeywordVocabulary

I signed the Contrigutor Agreement and can submit a PR to get things started. Maybe others can provide some valuable input?

**Comment by jensens** [comment]
Meanwhile solved in a slightly different way, see https://github.com/plone/plone.app.vocabularies#catalog
