### ISSUE TITLE
RelationChoice field leads to ValueError in principals

### ISSUE THREAD

**Issue by mtrebron** [plone/plone.app.vocabularies#59]
Dexterity types which include a RelationChoice field e.g. 

```
    <field name="teaser_image" type="z3c.relationfield.schema.RelationChoice">
      <description/>
      <required>False</required>
      <title>Teaser Image</title>
      <portal_type>
        <element>Image</element>
      </portal_type>
    </field>
```
lead to the following error in Plone 5.2 RC5
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 243, in publish
  Module ZPublisher.BaseRequest, line 523, in traverse
  Module ZPublisher.BaseRequest, line 330, in traverseName
  Module zope.traversing.namespace, line 165, in namespaceLookup
  Module plone.z3cform.traversal, line 54, in traverse
  Module plone.dexterity.browser.add, line 141, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module z3c.form.group, line 48, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module plone.app.z3cform.widget, line 443, in update
  Module z3c.form.browser.text, line 36, in update
  Module z3c.form.browser.widget, line 171, in update
  Module Products.CMFPlone.patches.z3c_form, line 47, in _wrapped
  Module z3c.form.widget, line 132, in update
  Module plone.app.z3cform.converters, line 181, in toWidgetValue
  Module plone.app.vocabularies.principals, line 147, in getTerm
  Module plone.app.vocabularies.principals, line 113, in _get_term_from_source
ValueError: value or token must be provided (only one of those)
```

**Comment by cekk** [comment]
I have the same problem with a custom field that is using CatalogSource as source.

What i don't understand, is why the view called by the widget tries to get the term of principals vocabulary.

**Comment by mtrebron** [comment]
> What i don't understand, is why the view called by the widget tries to get the term of principals vocabulary.

Because of this:
```
 [plone.app.z3cform.converters:180][waitress] <AjaxSelectWidget 'form.widgets.IDublinCore.creators'>
```

Maybe this issue belongs somewhere else: plone.app.z3cform or CMFPlone?

**Comment by petschki** [comment]
Looking at the RelatedItems behavior (https://github.com/plone/plone.app.relationfield/blob/master/plone/app/relationfield/behavior.py#L26) there is the widget directive with the vocabulary defined. So something like this should do the trick (untested!)

```
<field name="teaser_image" type="z3c.relationfield.schema.RelationChoice">
  <description/>
  <required>False</required>
  <title>Teaser Image</title>
  <form:widget type="plone.app.z3cform.widget.RelatedItemsFieldWidget">
      <vocabulary>plone.app.vocabularies.Catalog</vocabulary>
  </form:widget>
</field>
```

NOTE: the `pattern_options` parameter can define a `selectableTypes' list ... but I'm not shure how to define this in the XML schema ... 

and remember to add `xmlns:form="http://namespaces.plone.org/supermodel/form"` to the <model> prefixes...

**Comment by mtrebron** [comment]
Maybe a step in the right direction, no tracebacks...

With your suggestion in a TTW DX type:
1. initially, the selection is rooted in a LRF folder (correct)
2. a list of folderish types is displayed (correct)
3. entering a folder containing images yields no results, only an option to go back up the tree (unexpected)
4. clicking the home icon results in a "no items found" message and no way to go back to a LRF (unexpected)

The list of items in 2 can be restricted by adding a list of elements beneath the form
```
<portal_type>
    <element>Folder</element>
    <element>LRF</element>
    <element>LIF</element>
    <element>Image</element>
</portal_type>
```

**Comment by mtrebron** [comment]
The problem lies with the toWidgetValue converter not recognizing (None, ) as None and the lack of permissions on plone.app.vocabularies.Principals. The latter is required by a query of the form.widgets.IDublinCore.creators vocabulary - unclear why this is done...

**Comment by adrianschulz** [comment]
Any updates here? Is somebody working on this one?

**Comment by fulv** [comment]
By the way, I don't see the need to add a permission on plone.app.vocabularies.Principals, @mtrebron .
It works without for me.

**Comment by mtrebron** [comment]
@fulv correct, that permission is not necessary (anymore?).

**Comment by NicolasGoeddel** [comment]
Is this the same issue as this one? https://github.com/plone/plone.app.z3cform/issues/121

**Comment by mtrebron** [comment]
Yes, good catch. Will close as fixed by https://github.com/plone/plone.app.z3cform/pull/122
