### ISSUE TITLE
4.x vs master branch?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.vocabularies#68]
@mauritsvanrees @esteele (as you're the release managers)

- the current master targets the 4.3... series
- confusingly there is an 4.x branch 

Is this by accident, by intend, bad naming and 4.0.x was meant or what else? Any idea?

**Comment by mauritsvanrees** [comment]
Should probably have been called 4.0.x, maybe without the last few commits on this branch, as they are about Python 3 / Zope 4 compatibility.
